# Generated by Django 4.1.4 on 2022-12-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="app",
            fields=[
                (
                    "appid",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("appname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="behavior",
            fields=[
                (
                    "behid",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("beh", models.CharField(max_length=100)),
                ("npoint", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memid", models.IntegerField(default=0)),
                ("edate", models.DateTimeField(auto_now=True)),
                ("npoint", models.IntegerField(default=0)),
                ("elist", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="history",
            fields=[
                (
                    "hisid",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("ordid", models.IntegerField(default=0)),
                ("memid", models.IntegerField(default=0)),
                ("cdate", models.DateTimeField(auto_now=True)),
                ("gpoint", models.IntegerField(default=0)),
                ("amount", models.IntegerField(default=0)),
                ("appid", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memid", models.IntegerField(default=0)),
                ("rdate", models.DateTimeField(auto_now=True)),
                ("disc", models.CharField(max_length=1000)),
            ],
        ),
    ]
