# Generated by Django 4.1.4 on 2022-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_exchange_id_alter_exchange_memid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="edate",
            field=models.DateField(auto_now=True),
        ),
    ]
