# Generated by Django 4.1.4 on 2023-01-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_history_cdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="hisid",
        ),
        migrations.AddField(
            model_name="history",
            name="c_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="history",
            name="ordid",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
