# Generated by Django 4.1.4 on 2023-01-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_history_hisid_history_c_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="cdate",
            field=models.DateField(),
        ),
    ]
