# Generated by Django 4.1.4 on 2023-01-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_history_cdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="appid",
            field=models.CharField(max_length=100),
        ),
    ]
