# Generated by Django 4.1.4 on 2023-01-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_delete_app_rename_appid_history_appname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="history",
        ),
    ]
