# Generated by Django 4.1.4 on 2023-01-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_delete_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "ordid",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("memid", models.IntegerField(default=0)),
                ("cdate", models.DateField()),
                ("gpoint", models.IntegerField(default=0)),
                ("c_amount", models.IntegerField(default=0)),
                ("amount", models.IntegerField(default=0)),
                ("appname", models.CharField(max_length=100)),
            ],
        ),
    ]
