# Generated by Django 4.1.4 on 2023-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="history",
            name="ordid",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
